{{- define "my-hackerrank-chart.fullname" -}}
{{- printf "%s-%s" .Release.Name .Chart.Name }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "my-hackerrank-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hackerrank
  template:
    metadata:
      labels:
        app: hackerrank
    spec:
      containers:
      - name: hackerrank
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
      imagePullSecrets:
        - name: nodejs-registry-secret
      restartPolicy: Always

