apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "my-hackerrank-chart.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
