apiVersion: v1
kind: Service
metadata:
  name: {{ template "my-hackerrank-chart.fullname" . }}-service
spec:
  selector:
    app: hackerrank
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
